### PR TITLE
Portfolio: validate contact form

### PR DESCRIPTION
**Pull request by Bupilipili**
###In this branch.
-Added validation in the contact form that an error message will appear when the email-input will be anything other than in Lowercase.

### CODE REVIEW

**Review by algerina — COMMENTED** [review]
Hi team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that have Linters errors (Eslint)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by binhussen** [comment]
@Bupilipili and @GeekyHacks would you fix the eslint error as the previous code reviewer suggested
you can install `npm install --save-dev eslint@7.x eslint-config-airbnb-base@14.x eslint-plugin-import@2.x babel-eslint@10.x`
then you can fix it by using `npx eslint . --fix`

**Review by tufoinnkuo10 — CHANGES_REQUESTED** [review]
Hi @Bupilipili 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

please like the previous reviewer noted, your Eslint checks are failing. Remember they identify problematic patterns found in your code.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Bupilipili** [comment]
-already fixed the Eslinter error.

**Review by abdallahmalima — APPROVED** [review]
Hi @Bupilipili , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Check email lowercase✔️
- Validation error message✔️
- Linters setup✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
